src/api/config/routes.rb
# we take everything here that is not XML - the default mimetype is xml though
class WebuiMatcher

  class InvalidRequestFormat < APIException
  end

  def self.matches?(request)
    begin
      request.format.to_sym != :xml
    rescue ArgumentError => e
      raise InvalidRequestFormat.new e.to_s
    end
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    #Rails.logger.debug "MATCHES #{format}"
    format == :xml || format == :json
  end
end

OBSApi::Application.routes.draw do

  constraints(WebuiMatcher) do

    cons = {project: %r{[^\/]*}, package: %r{[^\/]*}, binary: %r{[^\/]*},
            user: %r{[^\/]*}, login: %r{[^\/]*}, title: %r{[^\/]*}, service: %r{\w[^\/]*},
            repository: %r{[^\/]*}, filename: %r{[^\/]*}, arch: %r{[^\/]*},
            id: %r{\d*}}

    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
      get 'main/add_news_dialog' => :add_news_dialog
      post 'main/add_news' => :add_news
      get 'main/delete_message_dialog' => :delete_message_dialog
      post 'main/delete_message' => :delete_message
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, as: :news_feed
      get 'main/latest_updates' => :latest_updates, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
    end

    controller 'webui/attribute' do
      get 'attribute/edit' => :edit
      post 'attribute/save' => :save
      match 'attribute/delete' => :delete, via: [:post, :delete]
    end

    controller 'webui/configuration' do
      get 'configuration/' => :index
      get 'configuration/users' => :users
      get 'configuration/groups' => :groups
      get 'configuration/connect_instance' => :connect_instance
      post 'configuration/save_instance' => :save_instance
      post 'configuration/update_configuration' => :update_configuration
      post 'configuration/update_architectures' => :update_architectures

      get 'configuration/notifications' => :notifications
      post 'configuration/notifications' => :update_notifications
    end

    controller 'webui/driver_update' do
      get 'driver_update/create' => :create
      get 'driver_update/edit' => :edit
      post 'driver_update/save' => :save
      get 'driver_update/binaries' => :binaries
    end

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events
    end

    controller 'webui/package' do
      get 'package/show/(:project/(:package))' => :show, as: 'package_show', constraints: cons
      get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons
      get 'package/dependency/:project/:package' => :dependency, constraints: cons
      get 'package/binary/:project/:package' => :binary, constraints: cons, as: 'package_binary'
      get 'package/binaries/:project/:package' => :binaries, constraints: cons, as: 'package_binaries'
      get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
      get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
      get 'package/statistics/:project/:package' => :statistics, as: 'package_statistics', constraints: cons
      get 'package/commit/:project/:package' => :commit, as: 'package_commit', constraints: cons
      get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
      get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons
      post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
      get 'package/add_person/:project/:package' => :add_person, constraints: cons
      get 'package/add_group/:project/:package' => :add_group, constraints: cons
      get 'package/rdiff/(:project/(:package))' => :rdiff, constraints: cons
      get 'package/wizard_new/:project' => :wizard_new, constraints: cons
      get 'package/wizard/:project/:package' => :wizard, constraints: cons
      post 'package/save_new/:project' => :save_new, constraints: cons
      get 'package/branch_dialog/:project/:package' => :branch_dialog, constraints: cons
      post 'package/branch/:project/:package' => :branch, constraints: cons
      post 'package/save_new_link/:project' => :save_new_link, constraints: cons
      post 'package/save/:project/:package' => :save, constraints: cons
      get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons
      post 'package/remove/:project/:package' => :remove, constraints: cons
      get 'package/add_file/:project/:package' => :add_file, constraints: cons
      post 'package/save_file/:project/:package' => :save_file, constraints: cons
      post 'package/remove_file/:project/:package' => :remove_file, constraints: cons
      post 'package/save_person/:project/:package' => :save_person, constraints: cons
      post 'package/save_group/:project/:package' => :save_group, constraints: cons
      post 'package/remove_role/:project/:package' => :remove_role, constraints: cons
      get 'package/view_file/(:project/(:package/(:filename)))' => :view_file, constraints: cons, as: 'package_view_file'
      post 'package/save_modified_file/:project/:package' => :save_modified_file, constraints: cons
      get 'package/live_build_log/(:project/(:package/(:repository/(:arch))))' => :live_build_log, constraints: cons
      get 'package/update_build_log/:project/:package' => :update_build_log, constraints: cons
      get 'package/abort_build/:project/:package' => :abort_build, constraints: cons
      delete 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons
      delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons
      get 'package/devel_project/:project/:package' => :devel_project, constraints: cons
      get 'package/buildresult' => :buildresult, constraints: cons
      get 'package/rpmlint_result' => :rpmlint_result, constraints: cons
      get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
      get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
      post 'package/save_meta/:project/:package' => :save_meta, constraints: cons
      get 'package/attributes/:project/:package' => :attributes, constraints: cons, as: 'package_attributes'
      get 'package/edit/:project/:package' => :edit, constraints: cons
      get 'package/repositories/:project/:package' => :repositories, constraints: cons
      post 'package/change_flag/:project/:package' => :change_flag, constraints: cons
      get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
      # compat route
      get 'package/files/:project/:package' => :show, constraints: cons
      post 'package/comments/:project/:package' => :save_comment, constraints: cons
    end

    controller 'webui/patchinfo' do
      post 'patchinfo/new_patchinfo' => :new_patchinfo
      post 'patchinfo/updatepatchinfo' => :updatepatchinfo
      get 'patchinfo/edit_patchinfo' => :edit_patchinfo
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show'
      get 'patchinfo/read_patchinfo' => :read_patchinfo
      post 'patchinfo/save' => :save
      post 'patchinfo/remove' => :remove
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/get_issue_sum' => :get_issue_sum
      get 'patchinfo/delete_dialog' => :delete_dialog
    end

    controller 'webui/project' do
      get 'project/' => :index
      get 'project/list_public' => :list_public
      get 'project/list_all' => :list_all
      get 'project/list' => :list
      get 'project/list_simple' => :list_simple
      get 'project/autocomplete_projects' => :autocomplete_projects
      get 'project/autocomplete_incidents' => :autocomplete_incidents
      get 'project/autocomplete_packages' => :autocomplete_packages
      get 'project/autocomplete_repositories' => :autocomplete_repositories
      get 'project/users/:project' => :users, constraints: cons, as: 'project_users'
      get 'project/subprojects/:project' => :subprojects, constraints: cons, as: 'project_subprojects'
      get 'project/attributes/:project' => :attributes, constraints: cons, as: 'project_attributes'
      get 'project/new' => :new
      post 'project/new_incident' => :new_incident
      get 'project/new_package/:project' => :new_package, constraints: cons
      get 'project/new_package_branch/:project' => :new_package_branch, constraints: cons
      get 'project/incident_request_dialog' => :incident_request_dialog
      post 'project/new_incident_request' => :new_incident_request
      get 'project/release_request_dialog' => :release_request_dialog
      post 'project/new_release_request/(:project)' => :new_release_request
      get 'project/show/(:project)' => :show, constraints: cons, as: 'project_show'
      get 'project/packages_simple/:project' => :packages_simple, constraints: cons
      get 'project/linking_projects/:project' => :linking_projects, constraints: cons
      get 'project/add_repository_from_default_list/:project' => :add_repository_from_default_list, constraints: cons
      get 'project/add_repository/:project' => :add_repository, constraints: cons
      get 'project/add_person/:project' => :add_person, constraints: cons
      get 'project/add_group/:project' => :add_group, constraints: cons
      get 'project/buildresult' => :buildresult, constraints: cons
      get 'project/delete_dialog' => :delete_dialog
      post 'project/delete' => :delete
      get 'project/edit_repository/:project' => :edit_repository
      post 'project/update_target/:project' => :update_target

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController

  include Webui::WebuiHelper
  # Apidocs is insensitive static information, no login needed therefore
  skip_before_filter :extract_user
  
  # the main purpose of this subfunction is easier stubing
  def indexpath
    filename = File.expand_path(CONFIG['apidocs_location']) + "/index"
    if !File.exist?( filename + ".html" )
      return nil
    else
      return filename
    end
  end

  def index
    filename = indexpath
    unless filename
      flash[:error] = "Unable to load API documentation source file: #{CONFIG['apidocs_location']}"
      redirect_back_or_to :controller => 'main', :action => 'index'
    else
      render :file => filename, formats: [:html]
    end
  end

  def file
    file = File.expand_path( File.join(CONFIG['schema_location'], params[:filename]) )
    if File.exist?( file )
      send_file( file, :type => "text/xml", :disposition => "inline" )
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back_or_to :controller => 'apidocs', :action => 'index'
    end
    return
  end

end

src/api/app/controllers/webui/attribute_controller.rb
class Webui::AttributeController < Webui::WebuiController
  helper :all
  before_filter :requires

  helper 'webui/project'

  def edit
    if @attributes.nil? # fails if package does not exist in project anymore
      redirect_to :controller => :project, :action => :attributes, :project => params[:project] and return
    end
    if params[:namespace] and params[:name]
      selected_attribute = nil
      atype = AttribType.find_by_namespace_and_name(params[:namespace], params[:name])
      selected_attribute = @attributes.where(attrib_type: atype).first
      unless selected_attribute
        redirect_to :back and return
      end
      @selected_attribute_name = '%s:%s' % [params[:namespace], params[:name]]
      @selected_attribute_value = selected_attribute.values 
    else
      @attribute_list = []
      AttribType.all.each do |d|
        @attribute_list << "#{d.attrib_namespace.name}:#{d.name}"
      end
      @attribute_list.sort!
    end
  end

  def save
    values = params[:values].split(',')
    namespace, name = params[:attribute].split(/:/)

    opt = { :action => :edit, :project => @project.name, package: params[:package] }

    unless User.current.can_create_attribute_in? @attribute_container, namespace: namespace, name: name
      redirect_to opt, error: 'No permission to save attribute'
      return
    end

    begin
      Attrib.transaction do
        @attribute_container.store_attribute(namespace, name, values, [])
        @attribute_container.write_attributes # save to backend
      end
    rescue APIException => e
      redirect_to opt, error: "Saving attribute failed: #{e.message}"
      return
    end

    if params[:package]
      opt = {:controller => :package, :action => :attributes, :project => @project.name, package: params[:package] }
    elsif params[:project]
      opt = {:controller => :project, :action => :attributes, :project => @project.name }
    end

    redirect_to opt, notice: 'Attribute sucessfully added!'
  end

  def delete
    required_parameters :namespace, :name

    if params[:package]
      opt = { :controller => :package, :action => :attributes, :project => @project.name, package: params[:package] }
    elsif params[:project]
      opt = { :controller => :project, :action => :attributes, :project => @project.name }
    end

    unless User.current.can_create_attribute_in? @attribute_container, namespace: params[:namespace], name: params[:name]
      redirect_to opt, error: 'Deleting attribute failed: no permission to change attribute'
      return
    end

    atype = AttribType.find_by_namespace_and_name(params[:namespace], params[:name]) 
    @attributes.where(attrib_type: atype).destroy_all
    redirect_to opt, notice: 'Attribute sucessfully deleted!'
  end

  private

  def requires
    required_parameters :project
    @project = WebuiProject.find(params[:project])
    unless @project && !@project.is_remote?
      flash[:error] = "Project not found: #{params[:project]}"
      redirect_to :controller => 'project', :action => 'list_public' and return
    end
    @is_maintenance_project = false
    @is_maintenance_project = true if @project.project_type and @project.project_type == 'maintenance'
    if params[:package]
      @package = @project.api_obj.find_package(params[:package])
      unless @package
        redirect_to project_show_path(@project.api_obj.name), error: "Package #{params[:package]} not found" and return
      end
      @attribute_container = @package
    else
      @attribute_container = @project.api_obj
    end
    @attributes = @attribute_container.attribs
  end
end

src/api/app/controllers/webui/comments_controller.rb
class Webui::CommentsController < Webui::WebuiController

  def destroy
    comment = Comment.find(params[:id])
    unless comment.check_delete_permissions
      flash[:error] = 'No permissions to delete comment'
      redirect_to :back
      return
    end
    comment.blank_or_destroy


    respond_to do |format|
      format.js { render json: 'ok' }
      format.html do
        flash[:notice] = 'Comment deleted successfully'
      end
    end
    redirect_to :back
  end

end

src/api/app/controllers/webui/feeds_controller.rb
class Webui::FeedsController < Webui::WebuiController

  include Webui::WebuiHelper
  include StatisticsCalculations

  layout false

  def news
    @news = StatusMessage.alive.limit(5)
    raise ActionController::RoutingError.new('expected application/rss') unless request.format == Mime::RSS
  end

  def latest_updates
    raise ActionController::RoutingError.new('expected application/rss') unless request.format == Mime::RSS
    @latest_updates = get_latest_updated(10)
  end

  def commits
    @project = Project.find_by_name(params[:project])
    if @project.nil?
      render(file: Rails.root.join('public/404'), status: 404, layout: false, formats: [:html])
      return
    end
    # The sourceaccess flag is checked for the project, but not for every package
    if !User.current.is_admin? && @project.disabled_for?('sourceaccess', nil, nil)
      render file: Rails.root.join('public/403'), formats: [:html], status: :forbidden, layout: false
      return
    end
    unless params[:starting_at].blank?
      @start = (Time.zone.parse(params[:starting_at]) rescue nil)
    end
    @start ||= 7.days.ago
    @finish = nil
    unless params[:ending_at].blank?
      @finish = (Time.zone.parse(params[:ending_at]) rescue nil)
    end
    @commits = @project.project_log_entries.where(event_type: 'commit').where(["datetime >= ?", @start])
    @commits = @commits.where(["datetime <= ?", @finish]) unless @finish.nil?
    @commits = @commits.order("datetime desc")
  end
end

src/api/app/helpers/webui/comment_helper.rb
module Webui::CommentHelper

  def save_comment_form
    opts = {action: 'save_comment'}
    opts[:controller] = params[:controller]
    opts[:project] = @project.name if @project
    opts[:package] = @package.to_param if @package
    opts[:id] = @id if @id
    form_tag(opts) do
      yield
    end
  end
end

src/api/app/helpers/webui/home_helper.rb
module Webui::HomeHelper
  include Webui::RequestHelper
end

src/api/app/views/webui/theme/bratwurst/webui/package/_commit.html.haml
- commit = @package.commit(rev.to_s)
- if commit
  .row
    .col-md-12
      %p
        - if commit['comment']
          = truncate(commit['comment'])
        - else
          No commit message
  .row
    .col-md-10
      %p
        -if commit['user'] == '_service'
          %i.fa.fa-cogs
          Automatic update
        - else
          - user = User.find_by_login commit['user']
          - if user
            = user_icon(user, 20, 'img-rounded')
            = link_to(user_show_path(user)) do
              = user.realname || user.login
          - else
            / hmm no user. whatever...
            %i.fa.fa-user
            = commit['user'] || 'unknown'
        - if commit['requestid']
          accepted
          = link_to("request #{commit['requestid']}", {:controller => :request, :action => :show, :id => commit['requestid']})
        - else
          authored
        = fuzzy_time(Time.at(commit['time'].to_i))
    .col-md-2
      %span.pull-right
        = link_to({:controller => :package, :action => :rdiff, :package => @package, :project => @project, :rev => commit['rev'], :linkrev => 'base'}) do
          revision #{commit['rev']}
- else
  %em
    Revision #{rev.to_s} not found

src/api/app/views/webui/theme/bratwurst/webui/package/_files.html.haml
.row
  .col-md-12
    .commit_header{:style=>"background-color: #f1f1f1;"}
      - unless @files.blank? or @spider_bot
        = render :partial => 'links' if (@linkinfo && !@linkinfo.has_attribute?('error'))
      .commit_item
        = render :partial => 'commit', :locals => {:rev => @revision}
.row
  .col-md-12
    - unless @files.blank?
      %table.table#files_table
        %thead
          %tr
            %th Filename
            %th Changed
        %tbody
          - @files.each do |file|
            %tr{:id=>"file-#{valid_xml_id(file[:name])}"}
              %td
                - link_opts = {action: :view_file, project: @project, package: @package, filename: file[:name], expand: @expand}
                - unless @is_current_rev
                  - link_opts[:rev] = file[:srcmd5]
                = link_to_if(file[:viewable], nbsp(file[:name]), link_opts)
              %td
                %span.hidden
                  #{file[:mtime]}
                = fuzzy_time_string(Time.at(file[:mtime].to_i).to_s)
              / limit download for anonymous user to avoid getting killed by crawlers
    - else
      %p
        %i
          This package has no files yet
    - if User.current.can_modify_package? @package
      %p
        = link_to sprite_tag('page_white_add'), :action => :add_file, :project => @project, :package => @package
        = link_to 'Add file', :action => :add_file, :project => @project, :package => @package

src/api/app/views/webui/theme/bratwurst/webui/package/show.html.haml
- content_for :title do
  Show #{@project} / #{@package}

- dpackage = @package.develpackage

.row
  .col-md-12
    .page-header
      .btn-group.pull-right
        = link_to({:action => :submit_request_dialog, :project => @project, :package => @package}, :remote => true, :class=>"btn btn-default btn-sm") do
          %i.fa.fa-plus
          Submit
        = link_to({:action => :branch_dialog, :project => @project, :package => @package}, :remote => true, :class=>"btn btn-default btn-sm") do
          %i.fa.fa-code-fork
          Branch
        = link_to({:action => :delete_dialog, :package => @package, :project => @project}, :remote => true, :class=>"btn btn-default btn-sm") do
          %i.fa.fa-minus
          Delete
      - title = @package.title
      - title = @package.name if title.blank?
      %h1
        %i.fa.fa-archive
        = link_to(@project) + " /"
        = link_to(@package.name, :controller => :package, :action=> 'show', :project => @project, :package => @package)
      .clearfix
.row
  .col-md-9
    %p.lead
      = @package.description
      - if User.current.can_modify_package? @package
        = link_to({:action => 'edit', :project => @project, :package => @package, :spec_count => @spec_count}, id: 'edit-description', :class =>"btn btn-default btn-xs" ) do
          %i.fa.fa-pencil
          Edit
          
  .col-md-3

.row
  .col-md-9
    .files{:style=>"background-color: #f9f9f9"}
      = render :partial => 'files'

- content_for :scripts do
  :javascript
    $('#').dataTable();